### ISSUE TITLE
Framerate 0 for capture device

### ISSUE THREAD

**Issue by mynameisfiber** [tschnz/Live-Video-Magnification#11]
When using a capture device, `this->imgProcSettings.framerate` is zero which leads to the Riesz maximum frequency in the UI being 0.

https://github.com/tschnz/Live-Video-Magnification/blob/master/src/main/ui/MagnifyOptions.cpp#L416-L419

This effectively makes this magnification method unusable for capture devices.

**Comment by tschnz** [comment]
This is fixed now so at least Riesz works on live streams but the Cutoff Wavelength and Frequencies to amplify are not based on the real world anymore see https://github.com/tschnz/Live-Video-Magnification/issues/16
