### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by nitoniso** [tschnz/Live-Video-Magnification#13]
Hi I have installed all the dependencies and added all directories and linkers in Visual Studio 2019 but I am still not able to compile this. I also tried using QT Studio but its all not working I keep on receiving errors.

I am getting error:

Error LNK1181 cannot open input file 'C:\Qt\Tools\QtDesignStudio\qt5_design_studio_reduced_version\lib\Qt5Widgets.lib' rvm C:\Users\taten\3D Objects\BBMA\Live-Video-Magnification-master\Live-Video-Magnification-master\src\LINK 1**_

I have tried serching for the libraries but i did not find them.

There are just .prl files and no .lib files in Qt\Tools\QtDesignStudio\qt5_design_studio_reduced_version\lib\

**Comment by tschnz** [comment]
This is changed to use CMake now, which should make it easier to compile. Please open a new Issue in case you still run into problems
