### ISSUE TITLE
Solved. Unable to use in Windows 10 64 bit

### ISSUE THREAD

**Issue by Ghaz75** [tschnz/Live-Video-Magnification#4]
Hello Dear
I am a paranormal Researcher and using your code in Debian I have captured a lot. My next step is to use your GUI in Windows 10 64 bit along with Kinect V2 without any virtual environment. I am unable to compile your code for Windows 10 64 bit using opencv 2, Qt 5 for windows under Visual Studio 2017. Each time I try to build from rvm.pro I get one error which seems to be logical as it points to a path in your code related to your own machine i.e  
Error	LNK1181	cannot open input file 'D:\Programme\OpenCV\source\opencv\install\x64\vc15\lib\opencv_core412.lib'	Coz I dont have this path existing in my machine. 
 If you kindly help me and release some pre-compiled binaries and executable for windows 10 64 bit, I shall be grateful. Being not a code Guru I need your help in this. Regards

**Comment by Ghaz75** [comment]
Dear ! Finally I compiled it successfully under MS Visual Studio 2017. One has to be careful for setting directory paths for Lib, Bin and Include for OpenCV. I used OpenCV 4.20 and I confirm that your code was successfully compiled and works with OpenCV 4.2.0 and Qt5.1.2. You also need QT VS Tool for MSVC 2017. I compiled it under 64 bit platform of Windows 10. Under C/C++ settings of QT VS Tool QT Settings, for linker Input file the path should be set to YourDrive:\opencv\build\x64\vc15\lib\opencv_world420.lib

**Comment by mgpawo** [comment]
@Ghaz75  I am trying to compile the code for ages now and it does not work for me. I followed your suggestions but something is still not right. It would be awesome if you could publish the compiled code for Windows! It would help a lot.

**Comment by tschnz** [comment]
Easiest would be using Qt + OpenCV as it is also suggested. 
Qt Creator should be favored over Visual Studio since library linking is easier here.
OpenCV > v4.0 is advised as some important variable names and enumeration names have changed. 
@mgpawo Did you follow a tutorial on how to compile OpenCV yourself together with Qt?

Closing this since its solved

**Comment by b0rt** [comment]
for future readers: this guide helped me a lot: https://wiki.qt.io/How_to_setup_Qt_and_openCV_on_Windows
