### ISSUE TITLE
CMakeFiles?

### ISSUE THREAD

**Issue by Thanh-Binh** [tschnz/Live-Video-Magnification#5]
I want to compile it in Ubuntu.
Do you have any CMakeFile for it?
Thanks

**Comment by tschnz** [comment]
There is no CMakeFile. QT offers a free cross-platform non-commercial community version which was also used for this project. Why not use this?

**Comment by Thanh-Binh** [comment]
Ok, but how can you compile your project in Ubuntu?
Do you use Makefile?

In the meantime,  I create a CMakeFile and use it, but have a compiling error like below.
Could you please help me? Thanks

CMakeFiles/videoMagnifyApp.dir/src/main/threads/PlayerThread.cpp.o: In function `PlayerThread::PlayerThread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, double)':
PlayerThread.cpp:(.text+0x91f): undefined reference to `vtable for PlayerThread'
CMakeFiles/videoMagnifyApp.dir/src/main/threads/PlayerThread.cpp.o: In function `PlayerThread::setROI(QRect)':
PlayerThread.cpp:(.text+0x1d07): undefined reference to `PlayerThread::maxLevels(int)'
CMakeFiles/videoMagnifyApp.dir/src/main/threads/PlayerThread.cpp.o: In function `PlayerThread::~PlayerThread()':
PlayerThread.cpp:(.text+0x1ef6): undefined reference to `vtable for PlayerThread'
CMakeFiles/videoMagnifyApp.dir/src/main/threads/PlayerThread.cpp.o: In function `PlayerThread::endOfFrame_action()':
PlayerThread.cpp:(.text+0x28a4): undefined reference to `PlayerThread::endOfFrame()'
PlayerThread.cpp:(.text+0x28c1): undefined reference to `PlayerThread::updateStatisticsInGUI(ThreadStatisticsData)'
CMakeFiles/videoMagnifyApp.dir/src/main/threads/PlayerThread.cpp.o: In function `PlayerThread::run()':
PlayerThread.cpp:(.text+0x319b): undefined reference to `PlayerThread::newFrame(QImage const&)'
PlayerThread.cpp:(.text+0x31dc): undefined reference to `PlayerThread::updateStatisticsInGUI(ThreadStatisticsData)'
PlayerThread.cpp:(.text+0x36f0): undefined reference to `PlayerThread::origFrame(QImage const&)'
CMakeFiles/videoMagnifyApp.dir/src/main/threads/ProcessingThread.cpp.o: In function `ProcessingThread::setROI(QRect)':
ProcessingThread.cpp:(.text+0x50d): undefined reference to `ProcessingThread::maxLevels(int)'
CMakeFiles/videoMagnifyApp.dir/src/main/threads/ProcessingThread.cpp.o: In function `ProcessingThread::ProcessingThread(SharedImageBuffer*, int)':
ProcessingThread.cpp:(.text+0x1147): undefined reference to `vtable for ProcessingThread'
CMakeFiles/videoMagnifyApp.dir/src/main/threads/ProcessingThread.cpp.o: In function `ProcessingThread::~ProcessingThread()':
ProcessingThread.cpp:(.text+0x1e79): undefined reference to `vtable for ProcessingThread'
CMakeFiles/videoMagnifyApp.dir/src/main/threads/ProcessingThread.cpp.o: In function `ProcessingThread::run()':
ProcessingThread.cpp:(.text+0x2d9e): undefined reference to `ProcessingThread::origFrame(QImage const&)'
ProcessingThread.cpp:(.text+0x2dbc): undefined reference to `ProcessingThread::newFrame(QImage const&)'
ProcessingThread.cpp:(.text+0x2e08): undefined reference to `ProcessingThread::updateStatisticsInGUI(ThreadStatisticsData)'
ProcessingThread.cpp:(.text+0x373d): undefined reference to `ProcessingThread::frameWritten(int)'
CMakeFiles/videoMagnifyApp.dir/src/main/threads/SavingThread.cpp.o: In function `SavingThread::SavingThread()':
SavingThread.cpp:(.text+0xc8e): undefined reference to `vtable for SavingThread'
CMakeFiles/videoMagnifyApp.dir/src/main/threads/SavingThread.cpp.o: In function `SavingThread::~SavingThread()':
SavingThread.cpp:(.text+0x174c): undefined reference to `vtable for SavingThread'
CMakeFiles/videoMagnifyApp.dir/src/main/threads/SavingThread.cpp.o: In function `SavingThread::run()':
SavingThread.cpp:(.text+0x2a5f): undefined reference to `SavingThread::updateProgress(int)'
SavingThread.cpp:(.text+0x2a9c): undefined reference to `SavingThread::endOfSaving()'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/CameraView.cpp.o: In function `CameraView::CameraView(QWidget*, int, SharedImageBuffer*)':
CameraView.cpp:(.text+0x2d): undefined reference to `vtable for CameraView'
CameraView.cpp:(.text+0x170): undefined reference to `CameraView::staticMetaObject'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/CameraView.cpp.o: In function `CameraView::connectToCamera(bool, int, int, int, int, int)':
CameraView.cpp:(.text+0x6e6): undefined reference to `CameraView::staticMetaObject'
CameraView.cpp:(.text+0x81a): undefined reference to `CameraView::staticMetaObject'
CameraView.cpp:(.text+0xb4d): undefined reference to `CameraView::setROI(QRect)'
CameraView.cpp:(.text+0xb58): undefined reference to `CameraView::newImageProcessingFlags(ImageProcessingFlags)'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/CameraView.cpp.o: In function `CameraView::newMouseData(MouseData)':
CameraView.cpp:(.text+0x3d35): undefined reference to `CameraView::staticMetaObject'
CameraView.cpp:(.text+0x3fed): undefined reference to `CameraView::setROI(QRect)'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/CameraView.cpp.o: In function `CameraView::newMouseDataOriginalFrame(MouseData)':
CameraView.cpp:(.text+0x5085): undefined reference to `CameraView::staticMetaObject'
CameraView.cpp:(.text+0x5325): undefined reference to `CameraView::setROI(QRect)'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/CameraView.cpp.o: In function `CameraView::handleContextMenuAction(QAction*)':
CameraView.cpp:(.text+0x566a): undefined reference to `CameraView::setROI(QRect)'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/CameraView.cpp.o: In function `CameraView::hideSettings()':
CameraView.cpp:(.text+0x574b): undefined reference to `CameraView::staticMetaObject'
CameraView.cpp:(.text+0x57d4): undefined reference to `CameraView::staticMetaObject'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/CameraView.cpp.o: In function `CameraView::record()':
CameraView.cpp:(.text+0x592d): undefined reference to `CameraView::staticMetaObject'
CameraView.cpp:(.text+0x5b00): undefined reference to `CameraView::staticMetaObject'
CameraView.cpp:(.text+0x5bc5): undefined reference to `CameraView::staticMetaObject'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/CameraView.cpp.o:CameraView.cpp:(.text+0x5cb3): more undefined references to `CameraView::staticMetaObject' follow
CMakeFiles/videoMagnifyApp.dir/src/main/ui/CameraView.cpp.o: In function `CameraView::~CameraView()':
CameraView.cpp:(.text+0x6753): undefined reference to `vtable for CameraView'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/MainWindow.cpp.o: In function `MainWindow::showAboutQtDialog()':
MainWindow.cpp:(.text+0x1b): undefined reference to `MainWindow::staticMetaObject'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/MainWindow.cpp.o: In function `MainWindow::~MainWindow()':
MainWindow.cpp:(.text+0x24c): undefined reference to `vtable for MainWindow'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/MainWindow.cpp.o: In function `MainWindow::addCodecs()':
MainWindow.cpp:(.text+0xf43): undefined reference to `MainWindow::staticMetaObject'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/MainWindow.cpp.o: In function `MainWindow::MainWindow(QWidget*)':
MainWindow.cpp:(.text+0x1419): undefined reference to `vtable for MainWindow'
MainWindow.cpp:(.text+0x1480): undefined reference to `MainWindow::staticMetaObject'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/MainWindow.cpp.o: In function `MainWindow::disconnectCamera(int)':
MainWindow.cpp:(.text+0x1e6a): undefined reference to `MainWindow::staticMetaObject'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/MainWindow.cpp.o: In function `MainWindow::showAboutDialog()':
MainWindow.cpp:(.text+0x200f): undefined reference to `MainWindow::staticMetaObject'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/MainWindow.cpp.o: In function `MainWindow::showHelpDialog()':
MainWindow.cpp:(.text+0x2193): undefined reference to `MainWindow::staticMetaObject'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/MainWindow.cpp.o: In function `MainWindow::connectToCamera()':
MainWindow.cpp:(.text+0x26c3): undefined reference to `MainWindow::staticMetaObject'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/MainWindow.cpp.o:MainWindow.cpp:(.text+0x26eb): more undefined references to `MainWindow::staticMetaObject' follow
CMakeFiles/videoMagnifyApp.dir/src/main/ui/VideoView.cpp.o: In function `VideoView::VideoView(QWidget*, QString)':
VideoView.cpp:(.text+0x2c): undefined reference to `vtable for VideoView'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/VideoView.cpp.o: In function `VideoView::loadVideo(int, int, int, double)':
VideoView.cpp:(.text+0x580): undefined reference to `VideoView::staticMetaObject'
VideoView.cpp:(.text+0x8f1): undefined reference to `VideoView::staticMetaObject'
VideoView.cpp:(.text+0xd94): undefined reference to `VideoView::setROI(QRect)'
VideoView.cpp:(.text+0xd9f): undefined reference to `VideoView::newImageProcessingFlags(ImageProcessingFlags)'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/VideoView.cpp.o: In function `VideoView::~VideoView()':
VideoView.cpp:(.text+0x1643): undefined reference to `vtable for VideoView'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/VideoView.cpp.o: In function `VideoView::newMouseData(MouseData)':
VideoView.cpp:(.text+0x37d5): undefined reference to `VideoView::staticMetaObject'
VideoView.cpp:(.text+0x3adc): undefined reference to `VideoView::setROI(QRect)'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/VideoView.cpp.o: In function `VideoView::newMouseDataOriginalFrame(MouseData)':
VideoView.cpp:(.text+0x4bd5): undefined reference to `VideoView::staticMetaObject'
VideoView.cpp:(.text+0x4ecc): undefined reference to `VideoView::setROI(QRect)'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/VideoView.cpp.o: In function `VideoView::handleContextMenuAction(QAction*)':
VideoView.cpp:(.text+0x50c2): undefined reference to `VideoView::setROI(QRect)'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/VideoView.cpp.o: In function `VideoView::stop()':
VideoView.cpp:(.text+0x516d): undefined reference to `VideoView::staticMetaObject'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/VideoView.cpp.o: In function `VideoView::pause()':
VideoView.cpp:(.text+0x529d): undefined reference to `VideoView::staticMetaObject'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/VideoView.cpp.o: In function `VideoView::play()':
VideoView.cpp:(.text+0x5397): undefined reference to `VideoView::staticMetaObject'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/VideoView.cpp.o: In function `VideoView::save_action()':
VideoView.cpp:(.text+0x5871): undefined reference to `VideoView::staticMetaObject'
VideoView.cpp:(.text+0x58a0): undefined reference to `VideoView::staticMetaObject'
CMakeFiles/videoMagnifyApp.dir/src/external/qxtSlider/qxtspanslider.cpp.o: In function `QxtSpanSliderPrivate::QxtSpanSliderPrivate()':
qxtspanslider.cpp:(.text+0xe): undefined reference to `vtable for QxtSpanSliderPrivate'
CMakeFiles/videoMagnifyApp.dir/src/external/qxtSlider/qxtspanslider.cpp.o: In function `QxtSpanSlider::QxtSpanSlider(QWidget*)':
qxtspanslider.cpp:(.text+0xaa3): undefined reference to `vtable for QxtSpanSlider'
CMakeFiles/videoMagnifyApp.dir/src/external/qxtSlider/qxtspanslider.cpp.o: In function `QxtSpanSlider::QxtSpanSlider(Qt::Orientation, QWidget*)':
qxtspanslider.cpp:(.text+0xbc3): undefined reference to `vtable for QxtSpanSlider'
CMakeFiles/videoMagnifyApp.dir/src/external/qxtSlider/qxtspanslider.cpp.o: In function `QxtSpanSlider::~QxtSpanSlider()':
qxtspanslider.cpp:(.text+0xcc3): undefined reference to `vtable for QxtSpanSlider'
CMakeFiles/videoMagnifyApp.dir/src/external/qxtSlider/qxtspanslider.cpp.o: In function `non-virtual thunk to QxtSpanSlider::~QxtSpanSlider()':
qxtspanslider.cpp:(.text+0xd23): undefined reference to `vtable for QxtSpanSlider'
CMakeFiles/videoMagnifyApp.dir/src/external/qxtSlider/qxtspanslider.cpp.o: In function `QxtSpanSlider::setSpan(int, int)':
qxtspanslider.cpp:(.text+0xef6): undefined reference to `QxtSpanSlider::lowerValueChanged(int)'
qxtspanslider.cpp:(.text+0xf1a): undefined reference to `QxtSpanSlider::upperValueChanged(int)'
qxtspanslider.cpp:(.text+0xf31): undefined reference to `QxtSpanSlider::spanChanged(int, int)'
CMakeFiles/videoMagnifyApp.dir/src/external/qxtSlider/qxtspanslider.cpp.o: In function `QxtSpanSlider::setUpperPosition(int)':
qxtspanslider.cpp:(.text+0x10b6): undefined reference to `QxtSpanSlider::upperPositionChanged(int)'
CMakeFiles/videoMagnifyApp.dir/src/external/qxtSlider/qxtspanslider.cpp.o: In function `QxtSpanSlider::setLowerPosition(int)':
qxtspanslider.cpp:(.text+0x14f6): undefined reference to `QxtSpanSlider::lowerPositionChanged(int)'
CMakeFiles/videoMagnifyApp.dir/src/main/threads/CaptureThread.cpp.o: In function `CaptureThread::updateFPS(int)':
CaptureThread.cpp:(.text+0x488): undefined reference to `CaptureThread::updateFramerate(double)'
CMakeFiles/videoMagnifyApp.dir/src/main/threads/CaptureThread.cpp.o: In function `CaptureThread::CaptureThread(SharedImageBuffer*, int, bool, int, int, int)':
CaptureThread.cpp:(.text+0x58a): undefined reference to `vtable for CaptureThread'
CMakeFiles/videoMagnifyApp.dir/src/main/threads/CaptureThread.cpp.o: In function `CaptureThread::run()':
CaptureThread.cpp:(.text+0x84e): undefined reference to `CaptureThread::updateStatisticsInGUI(ThreadStatisticsData)'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/CameraConnectDialog.cpp.o: In function `CameraConnectDialog::~CameraConnectDialog()':
CameraConnectDialog.cpp:(.text+0x3): undefined reference to `vtable for CameraConnectDialog'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/CameraConnectDialog.cpp.o: In function `non-virtual thunk to CameraConnectDialog::~CameraConnectDialog()':
CameraConnectDialog.cpp:(.text+0x33): undefined reference to `vtable for CameraConnectDialog'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/CameraConnectDialog.cpp.o: In function `CameraConnectDialog::getDeviceNumber()':
CameraConnectDialog.cpp:(.text+0x105): undefined reference to `CameraConnectDialog::staticMetaObject'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/CameraConnectDialog.cpp.o: In function `CameraConnectDialog::getImageBufferSize()':
CameraConnectDialog.cpp:(.text+0x625): undefined reference to `CameraConnectDialog::staticMetaObject'
CameraConnectDialog.cpp:(.text+0x76f): undefined reference to `CameraConnectDialog::staticMetaObject'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/CameraConnectDialog.cpp.o: In function `CameraConnectDialog::openButton_clicked()':
CameraConnectDialog.cpp:(.text+0xb2d): undefined reference to `CameraConnectDialog::staticMetaObject'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/CameraConnectDialog.cpp.o: In function `CameraConnectDialog::CameraConnectDialog(QWidget*)':
CameraConnectDialog.cpp:(.text+0xde1): undefined reference to `vtable for CameraConnectDialog'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/FrameLabel.cpp.o: In function `FrameLabel::~FrameLabel()':
FrameLabel.cpp:(.text+0x3): undefined reference to `vtable for FrameLabel'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/FrameLabel.cpp.o: In function `non-virtual thunk to FrameLabel::~FrameLabel()':
FrameLabel.cpp:(.text+0x43): undefined reference to `vtable for FrameLabel'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/FrameLabel.cpp.o: In function `FrameLabel::mouseReleaseEvent(QMouseEvent*)':
FrameLabel.cpp:(.text+0x366): undefined reference to `FrameLabel::newMouseData(MouseData)'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/FrameLabel.cpp.o: In function `FrameLabel::createContextMenu()':
FrameLabel.cpp:(.text+0x654): undefined reference to `FrameLabel::staticMetaObject'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/FrameLabel.cpp.o: In function `FrameLabel::FrameLabel(QWidget*)':
FrameLabel.cpp:(.text+0x863): undefined reference to `vtable for FrameLabel'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/FrameLabel.cpp.o: In function `FrameLabel::mouseMoveEvent(QMouseEvent*)':
FrameLabel.cpp:(.text+0x174): undefined reference to `FrameLabel::onMouseMoveEvent()'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/MagnifyOptions.cpp.o: In function `MagnifyOptions::~MagnifyOptions()':
MagnifyOptions.cpp:(.text+0x3): undefined reference to `vtable for MagnifyOptions'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/MagnifyOptions.cpp.o: In function `non-virtual thunk to MagnifyOptions::~MagnifyOptions()':
MagnifyOptions.cpp:(.text+0x33): undefined reference to `vtable for MagnifyOptions'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/MagnifyOptions.cpp.o: In function `MagnifyOptions::updateSettingsFromOptionsTab()':
MagnifyOptions.cpp:(.text+0x4f4): undefined reference to `MagnifyOptions::newImageProcessingSettings(ImageProcessingSettings)'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/MagnifyOptions.cpp.o: In function `MagnifyOptions::setMaxLevel(int)':
MagnifyOptions.cpp:(.text+0x151c): undefined reference to `MagnifyOptions::newImageProcessingSettings(ImageProcessingSettings)'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/MagnifyOptions.cpp.o: In function `MagnifyOptions::MagnifyOptions(QWidget*)':
MagnifyOptions.cpp:(.text+0x155b): undefined reference to `vtable for MagnifyOptions'
CMakeFiles/videoMagnifyApp.dir/src/main/ui/MagnifyOptions.cpp.o: In function `MagnifyOptions::updateFlagsFromOptionsTab()':
MagnifyOptions.cpp:(.text+0x42a): undefined reference to `MagnifyOptions::newImageProcessingFlags(ImageProcessingFlags)'

**Comment by tschnz** [comment]
I do not use a Makefile, I compile it with QT.
Your problem is that you try to use CMake. Do not use CMake.

Install QT, open the QT project file (/src/rvm.pro), adjust it so that it points to your OpenCV libs, then compile.

**Comment by tschnz** [comment]
Closing bc this is not an issue that affects this project
