### ISSUE TITLE
Riesz magnification for baby sleeping does not work

### ISSUE THREAD

**Issue by Thanh-Binh** [tschnz/Live-Video-Magnification#6]
I tested your SW for the video baby sleeping from MIT, but do not see any magnification.
Here is my setting parameters:
pyramid level = 4
amplification = 50
Cutoff wave length 5
Freq low 0.04, high: 0.4 

Moreover, I am interested in understanding why do you use lowpass and highpass filter within riesz pyramid (by building and reconstruction)?

What do you think?
Thanks

**Comment by tschnz** [comment]
Hey,

your Cutoff Wavelength is too low. The rule is - the smaller the cutoff wl, the bigger the spatial image features have to be to be amplified.

High- and Lowpass are needed to generate the pyramid, as described in their [paper](https://people.csail.mit.edu/nwadhwa/riesz-pyramid/RieszPyr.pdf) in Sec. 3.2, originating from [Simoncelli et al.](https://www.researchgate.net/profile/Eero_Simoncelli/publication/3666212_The_steerable_pyramid_A_flexible_architecture_for_multi-scale_derivative_computation/links/542173b00cf203f155c6bf12/The-steerable-pyramid-A-flexible-architecture-for-multi-scale-derivative-computation.pdf)

**Comment by Thanh-Binh** [comment]
Thanks,
I Also find out this solution and change the max values from your GUI
BR Binh

Gesendet mit der 1&1 Mail App

Am 21.03.20 um 20:28 schrieb Jens Schindel
