### ISSUE TITLE
Idea filter frequency

### ISSUE THREAD

**Issue by hpwang22** [tschnz/Live-Video-Magnification#7]
Hi,
I have 2 questions about the idea filter frequency

double fl = 2 * cutoffLo * width / framerate;
double fh = 2 * cutoffHi * width / framerate;

why do you use 2 time frequency?
fl and fh are calculated by width instead of width and height, why?

Thanks a lot.

**Comment by tschnz** [comment]
The image is reshaped, meaning every row represents a pixel in the original image and every column represents a frame (eg the time axis). When creating the ideal filter, you can see that a row-wise DFT is applied, meaning, to correctly create the filter response length, we only need the time axis length, which is the length of the reshaped image.
